### ISSUE TITLE
Files named inconsistently

### ISSUE THREAD

**Issue by cdemyanovich** [ericdrosado/JS-Tic-Tac-Toe#18]
Some file names start with an uppercase letter and some a lowercase letter. Why the difference?

**Comment by ericdrosado** [comment]
Is this in reference to files in the src folder and spec folder?

**Comment by cdemyanovich** [comment]
Yes.

**Comment by ericdrosado** [comment]
Made the change to my UI.js file, which was originally ui.js. index.js and test.js i left the same as I assume this is the normal convention, but let me know if I'm wrong.
